"""Write each command's usage and options into its page in docs/commands, from the CLI itself.

Each page holds a block between `<!-- options -->` and `<!-- /options -->` that this script
owns; everything else on the page is written by hand. Run it after changing a command's
options or help texts. `--check` changes nothing and exits 1 when a page is out of date, as
the tests do.

    uv run python scripts/cli_docs.py [--check]
"""

from __future__ import annotations

import sys
from enum import Enum
from pathlib import Path
from typing import Any

import typer
from rich.text import Text

from jira_time_tracker.cli import app

ROOT = Path(__file__).resolve().parents[1]
PAGES = ROOT / "docs" / "commands"
START, END = "<!-- options -->", "<!-- /options -->"


# Typer's click objects, typed loosely: recent Typer versions bundle their own click.
Command = Any
Param = Any


def commands() -> dict[str, Command]:
    """Return every runnable command, keyed by its name after `jtt` ('config show')."""
    found: dict[str, Command] = {}

    def walk(command: Command, path: list[str]) -> None:
        if hasattr(command, "commands"):  # a group
            for name, sub in command.commands.items():
                walk(sub, [*path, name])
        else:
            found[" ".join(path)] = command

    walk(typer.main.get_command(app), [])
    return found


def slug(name: str) -> str:
    """Return the page, tape and GIF name for a command: 'config show' → 'config-show'."""
    return name.replace(" ", "-")


def _plain(markup: str | None) -> str:
    return " ".join(Text.from_markup(markup or "").plain.split())


def _is_option(param: Param) -> bool:
    return param.param_type_name == "option"


def _metavar(param: Param) -> str:
    if param.is_flag or param.count:
        return ""
    choices = getattr(param.type, "choices", None)
    if choices:
        return "[" + "|".join(str(getattr(c, "value", c)) for c in choices) + "]"
    name = str(param.type.name).removesuffix(" range")
    return {"str": "TEXT", "int": "INTEGER"}.get(name, name).upper()


def _limits(param: Param) -> str:
    low, high = getattr(param.type, "min", None), getattr(param.type, "max", None)
    if low is None and high is None:
        return ""
    if high is None:
        return f" At least {low:g}."
    return f" From {low:g} to {high:g}." if low is not None else f" At most {high:g}."


def _default(param: Param) -> str:
    if _is_option(param) and param.prompt:
        return "prompted"
    if param.required:
        return "required"
    value = param.default
    if isinstance(value, Enum):
        value = value.value
    if value is None or value is False or value == "":
        return ""
    if _is_option(param) and param.count and not value:
        return ""
    return f"`{value}`"


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def options_block(name: str, command: Command) -> str:
    """Return the generated block for one command."""
    arguments = [p for p in command.params if not _is_option(p)]
    usage = " ".join(
        ["jtt", name, *(a.human_readable_name.upper() for a in arguments), "[OPTIONS]"]
    )
    lines = [
        START,
        "<!-- Generated by scripts/cli_docs.py from the CLI: edit the help texts in cli.py. -->",
        "",
        "```text",
        usage,
        "```",
        "",
        "| Option | Default | Description |",
        "|---|---|---|",
    ]
    for param in command.params:
        if _is_option(param) and param.hidden:
            continue
        if _is_option(param):
            names = sorted(param.opts, key=len) + param.secondary_opts
            metavar = _metavar(param)
            spelled = ", ".join(f"`{n}`" for n in names) + (f" `{metavar}`" if metavar else "")
            help_text = _plain(param.help) + _limits(param)
        else:  # Typer's arguments carry a help text too
            spelled = f"`{param.human_readable_name.upper()}`"
            help_text = _plain(getattr(param, "help", ""))
        lines.append(f"| {_cell(spelled)} | {_default(param)} | {_cell(help_text.strip())} |")
    lines.append("| `-h`, `--help` |  | Show the command's help and exit. |")
    lines.append(END)
    return "\n".join(lines)


def update(page: Path, block: str) -> str:
    """Return the page's text with its generated block replaced."""
    text = page.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit(f"{page.relative_to(ROOT)}: no {START} … {END} block")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


def main(check: bool) -> int:
    """Rewrite (or check) every command page; return the exit status."""
    stale = []
    for name, command in commands().items():
        page = PAGES / f"{slug(name)}.md"
        if not page.exists():
            stale.append(f"{page.relative_to(ROOT)}: missing, for `jtt {name}`")
            continue
        new = update(page, options_block(name, command))
        if new != page.read_text(encoding="utf-8"):
            stale.append(
                f"{page.relative_to(ROOT)}: options {'out of date' if check else 'updated'}"
            )
            if not check:
                page.write_text(new, encoding="utf-8")
    for line in stale:
        print(line)
    return 1 if check and stale else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
